spring.application.name=taskProject

# DB connect
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = TRUE
spring.jpa.properties.hibernate.show_sql = TRUE

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# Security
spring.security.user.name=admin
spring.security.user.password=admin

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBRE1JTiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTczNjk1MDM3NiwiZXhwIjoxNzY4NDg2Mzc2fQ.x8u7nPK9zmB6gHxSRsDVOc5riE7fgGs_kg-ErU0Ypjo

